pipeline{
    agent any
    tools{
        maven 'maven-3.9.6'
    }
    stages{
        stage('GIT'){
            steps{
                git branch: 'main', url: 'https://github.com/kosaraju3333/spring-cloud-kubernetes.git'
            }
        }
        stage('Build-MVN'){
            steps{
                dir("kubernetes-configmap-reload"){
                    sh 'mvn clean package'
                }
            }
        }
        stage('Docker-Build'){
            steps{
                dir("kubernetes-configmap-reload"){
                    sh 'docker build -t kosaraju333/kubernetes-configmap-reload .'
                }
            }
        }
        stage('Docker-Push'){
            steps{
                dir("kubernetes-configmap-reload"){
                    sh 'docker tag kosaraju333/kubernetes-configmap-reload:latest kosaraju333/kubernetes-configmap-reload:V_0.1'
                    sh 'docker push kosaraju333/kubernetes-configmap-reload:V_0.1'
                }
            }
        }
    }
}
